// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UTILITY PLUGINS","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"YEP_GridFreeDoodads","status":true,"description":"v1.05 Place Grid-Free Doodads into your game using an\nin-game editor. Static and animated doodads can be used!","parameters":{"---General---":"","Doodads Folder":"img/doodads/","Doodads Smoothing":"false","Alphabetical Settings":"false","---Grid Snap---":"","Default Grid Snap":"true","Grid Snap Width":"24","Grid Snap Height":"24"}}
];
